url: "https://mesagrey.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "greymesa" # the name of your site, e.g. ACME Corp.
excerpt_separator: <!--ex-->
